# Generated by Django 6.0.3 on 2026-04-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
